[[services]]
  http_checks = []
  internal_port = 8043
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true  # optional

