name: manual destroy fly.io app

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'app name to destroy'
        default: 'pr-41-sky172839465-integration-example'
        required: true
        type: string

jobs:
  Destroy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Destroy app ${{ inputs.app }}"

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl apps destroy ${{ inputs.app }} --yes --verbose
