name: pr_close
on:
  pull_request:
    types: [closed]
permissions:
  actions: write
  contents: write
  pull-requests: write
  id-token: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  clean_up:
    name: Clean up
    runs-on: ubuntu-latest
    steps:
      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pr-${{ github.event.number }}
