name: "Bump Version"

on:
  push:
    branches:
      - "master"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  bump-version:
    name: "Bump Version"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          version-type: "minor"
          target-branch: "main"
          tag-prefix: "v"
          commit-message: "ci: bumps version to {{version}} [skip ci]"
