apiVersion: v1alpha
kind: puppeteer
sauce:
  region: us-west-1
  concurrency: 2
  metadata:
    name: Testing Puppeteer Support
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
docker:
  fileTransfer: copy
rootDir: ./__e2e__
puppeteer:
  version: 8.0.0
image:
  base: saucelabs/stt-puppeteer-jest-node
  version: latest
suites:
  - name: "chrome"
    testMatch: ["**/*.test.js"]
    browser: "chrome"
  - name: "firefox"
    testMatch: ["**/*.test.js"]
    browser: "firefox"
